### ISSUE TITLE
Toggle on switch indicator appears to be wrongly positioned

### ISSUE THREAD

**Issue by Cryptoford** [Polkadex-Substrate/polkadex-mobile-app#111]
This current setup of the toggle switch appears to be positioned wrongly.![Screenshot_20220224-160848.png](https://user-images.githubusercontent.com/90802124/155551587-9c47e8aa-4e74-48d8-8827-3d4e883cafa1.png)

**Comment by simonsso** [comment]
Hi @Cryptoford, please tell us how you interpret this switch? (I am too involved to see it clearly from an outside perspective as I know what we intended it to do, please help us improve)

**Comment by Cryptoford** [comment]
The faded color section of the switch appears to be positioned on the right. Which I suggest should be placed on the left side as often seen in conventional systems to indicate that the feature to use Dex to pay fee at a discount is turned off.
Implying that a user taps the _switch on_ by tapping it to the right (**not to the left as it is currently positioned**).
