### ISSUE TITLE
Removing filled orders from open orders. create separate filled orders tab.

### ISSUE THREAD

**Issue by Cryptoford** [Polkadex-Substrate/polkadex-mobile-app#116]
In this current iteration, every filled order get listed together with open orders immediately after each trade, creating confusion for the user.
But I observe the filled order no longer shows up in the open order tab if the user interacts with a different tab and then returns to the open order tap to check.
I could not find a separate filled order tab in this current iteration,  creating a separate tab would be more intuitive.

**Comment by pavankanteti** [comment]
@Hounsette Looks like a backend issue.
