### ISSUE TITLE
observed numeric variation in market order trades on the order book 

### ISSUE THREAD

**Issue by Cryptoford** [Polkadex-Substrate/polkadex-mobile-app#119]
Hello,
I observed a numeric variation **after** market orders trades are completed on the order book when compared to limit order trades.
S1 > shows before placing a BUY trade using limit order trades to a corresponding open SELL order on the order book.
![Screenshot_20220302-150524~2.png](https://user-images.githubusercontent.com/90802124/156400905-90a8cd84-b320-4d07-80f4-af6bd1a87eec.png)

S2 > shows a complete/correct deduction occurs after the limit trade is placed. That is, **111.5880 (corresponding open SELL order on the order book) - 11 (corresponding PDG buy order) = 100**

![Screenshot_20220302-150640~2.png](https://user-images.githubusercontent.com/90802124/156401015-85ae1627-7171-46ea-8f3f-93c17d09fb54.png)

The numeric variation issue was observed from this point. 👇

S3> shows before market BUY trade of 50 PDG; with a corresponding open SELL order of 100 SDX below.

![Screenshot_20220302-150640~3.png](https://user-images.githubusercontent.com/90802124/156401046-e2e8d497-aed8-4a59-96fc-bf52e468b488.png)

S4> resulting deduction after placing market order isn't same as limit order placed earlier. That is, expected order book engine should match orders as 100-50 = 50 SDX left on open sell orders. 

![Screenshot_20220302-150657~2.png](https://user-images.githubusercontent.com/90802124/156401084-186bbb4c-8a31-4925-a07d-8700e5e3bf21.png)

I believe something is not right here both from the UI and backend because instead of matching to fill available corresponding open sell order of 50 PDG (although the Header says SDX which is likely a display error), only about 21 PDG was filled from the order book, instead of 50 PDG.

Some clarification would be appreciated.

**Comment by simonsso** [comment]
This likely an issue with the mobile frontend, the limit for a market orders is given as the amount to spend to the backend. We will look into this.
