### ISSUE TITLE
UI/UX related; repositioning of Summary section of wallet balance.

### ISSUE THREAD

**Issue by Cryptoford** [Polkadex-Substrate/polkadex-mobile-app#121]
![Screenshot_20220302-172511.png](https://user-images.githubusercontent.com/90802124/156404201-bd87c045-30a8-4fa1-baa9-ebad33f8a8be.png)

The tab icon appears to be too faded despite being intended to provide a meaningful Summary of wallet balance.

Users will most likely find it difficult to recognize the purpose of the icon with this current icon design (with exception of having an app tour guide explaining this and other icons).

**Comment by simonsso** [comment]
Give it some colour
