### ISSUE TITLE
Prompt for password/biomeric to decrypt private key

### ISSUE THREAD

**Issue by Gauthamastro** [Polkadex-Substrate/polkadex-mobile-app#2]
The user should be prompted for the password when the user comes back to the app after

1. minimizing the app
2. closes and reopens the app

NOTE: the decrypted mnemonic or keypair object should be deleted from memory and not stored in the device storage.

**Comment by pavankanteti** [comment]
Waiting for screens from Rodolfo

**Comment by simonsso** [comment]
A good user experience is to allow user to lock screen and open with biometric login. 

In Android this is how it is done: Keys are stored in a Keystore which is an app in TEE (trusted execution environment) the biometric subsystem (Biometric Prompt) authenticates the user and release the key to the app.

https://developer.android.com/codelabs/biometric-login#0
https://medium.com/androiddevelopers/using-biometricprompt-with-cryptoobject-how-and-why-aace500ccdb7

ios looks to be working in the same way:
https://developer.apple.com/documentation/localauthentication/accessing_keychain_items_with_face_id_or_touch_id

**Comment by AdrielVBomfim** [comment]
I've alredy setup a dependency in the project to store biometrics and other necessary things called [FlutterSecureStorage](https://pub.dev/packages/flutter_secure_storage). It essentially uses the same stores in Android/iOS as biometric_storage.

**Comment by simonsso** [comment]
One reason for re-prompt on reopen is privacy if someone when a phone is unlocked and the user logded in nothing can be seen until reauthenticated.

It would be nice to have re-prompt-on-use as a user option but at this point I don't want us to spend time on this extra logic. With biometrics it will be less annoying for the user
