### ISSUE TITLE
Set up CI/ CD for this flutter project

### ISSUE THREAD

**Issue by Gauthamastro** [Polkadex-Substrate/polkadex-mobile-app#3]
Follow the best practices of CI/ CD for the flutter projects. 

Reference: 
1. https://flutter.dev/docs/deployment/cd

**Comment by AdrielVBomfim** [comment]
![Captura de tela 2021-07-13 113722](https://user-images.githubusercontent.com/38893955/125471549-62ab352a-6364-41b7-a313-6d5ac023b9bc.jpg)

Succesfully created a github actions script which checks for formatting issues and errors in the code, then builds the app to create .apk and .ipa files and upload to the artifacts associated with the workflow.

**Comment by AdrielVBomfim** [comment]
@Gauthamastro It would be cool if we could follow the best practices in our dart code. To do that, I'm trying to set a analysis_options.yaml file containing the lint rules recommended by Google (https://github.com/dart-lang/lints). When I do that, a lot of warnings are detected in the whole code, can I correct them and commit on the PR related to this issue?

**Comment by Gauthamastro** [comment]
Yes implement the workflow file in this PR. Create a separate issue for fixing lint errors and then raise another PR for that after this.
